name = "try-elysia"
main = "src/runtime/workerd.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public" }

[[kv_namespaces]]
binding = "try-elysia"
